### ISSUE TITLE
Application commands channel members

### ISSUE THREAD

**Issue by ihulsbus** [bwmarrin/discordgo#1146]
Hello, I can't seem to find it in the module's documentation, but is there a way I can retrieve all the members of a guild text channel based on the execution location of a slash command?

Additionally is there a way I can bind such a command to a specific channel?

Thanks!

**Comment by FedorLap2006** [comment]
Documentation lies [here](https://pkg.go.dev/github.com/bwmarrin/discordgo) (also you might want to read (Discord API docs](https://discord.dev) since DiscordGo is 1:1 of the API).

As for retrieving all members of a text channel, there is no easy way currently to do that in DiscordGo, however you can use [List Guild Members endpoint](https://discord.com/developers/docs/resources/guild#list-guild-members) to get all guild members, then filter them by checking roles which have access to the channel (overrides + admin rights).
