### ISSUE TITLE
Unable to get Message contents - always empty

### ISSUE THREAD

**Issue by OlegGulevskyy** [bwmarrin/discordgo#1249]
As subject line states, message content is always empty while I get, for example, message Author.
Here is a reproduction code:
https://github.com/OlegGulevskyy/discordgo

**Comment by FedorLap2006** [comment]
This is due to newly [introduced](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ) Message Content intent.
You can enable it using `s.Identify.Intents |= discordog.IntentMessageContent`. However, you also need to enable it in the developer dashboard, and after reaching 75 servers you would also need to apply for it.

P.S. It is highly recommended to use slash commands nowdays.

**Comment by OlegGulevskyy** [comment]
Thanks for your reply @FedorLap2006 
Sorry if this is obvious question, I am not too familiar with Discord, but you are saying it is highlighy recommended to go with slash commands. Are there any examples of recommended ways or documentation that I can refer to?

**Comment by FedorLap2006** [comment]
> Thanks for your reply @FedorLap2006 Sorry if this is obvious question, I am not too familiar with Discord, but you are saying it is highlighy recommended to go with slash commands. Are there any examples of recommended ways or documentation that I can refer to?

There are a couple. I would recommend to start with [slash_commands](https://github.com/bwmarrin/discordgo/blob/master/examples/slash_commands/main.go).

**Comment by OlegGulevskyy** [comment]
> > Thanks for your reply @FedorLap2006 Sorry if this is obvious question, I am not too familiar with Discord, but you are saying it is highlighy recommended to go with slash commands. Are there any examples of recommended ways or documentation that I can refer to?
> 
> There are a couple. I would recommend to start with [slash_commands](https://github.com/bwmarrin/discordgo/blob/master/examples/slash_commands/main.go) one.


Thank you!
