### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by genc-pluspeter** [bwmarrin/discordgo#1323]
Having memory leak in my service that only gets voice events from discord channels and publishes them via pubsub.
We started seeing that on 29th 05:00PM EST
We also had a lot more HTTP 404 errors (channel not found) getting back from discord.

**Comment by genc-pluspeter** [comment]
![image](https://user-images.githubusercontent.com/102214093/216549377-a4a6ab71-a925-41dd-a490-22e4a06a358f.png)

- The Memory usage has started to increase in a linear way from 29th of Jan 5 PM  sharp

- The only thing the service is doing is listening to some discord channels and publishing them to a message queue

- The break points are where the service has been restarted so it went from using 0.05GiB to 4GiB (which is enormous) 

- Since timing is a bit suspicious I wanted to ask if discord has made any changes because the service was running for  almost 1 year (11months) without any change and all of a sudden it started leaking.

I tried updating the discordgo lib to the latest version (which is using discord v9 API) and the leakage won't stop (can be seem in the last restart)
So my main question is: 
**Is anyone experiencing something similar? Does anyone have any suggestions?**
We also have an in-memory map in the service but i doubt it could start acting up because it has been 11 months and the memory was constantly kept at 0.05GiB

**Comment by FedorLap2006** [comment]
Since you have closed the issue. What was the problem?

**Comment by jonmol** [comment]
We aren't sure how it started, but at 29th we started getting the memory spikes as shown in the image. It turns out it was from a piece of code using Discord-go v0.23.2 that was making a user lookup, and that request locked a go routine every time.
We managed to remove the lookup, so we're not entering that situation, and at the same time looking at upgrading the library and using contexts and/or handle retries ourselves. 
I have no idea what happened on the 29th though, the code was compiled 11 months ago and the server in question hasn't had a spike of users. Guess it's either a change in the enforcement of rate limits, or that we were unlucky to have reached a point were we're just short of being able to honour it.
