### ISSUE TITLE
SelectMenu::MinValues type should be int instead of *int?

### ISSUE THREAD

**Issue by Spaceenter** [bwmarrin/discordgo#1485]
https://github.com/bwmarrin/discordgo/blob/v0.27.1/components.go#L198C2-L198C11

MaxValues below is of type int, but MinValues is of type *int --> This seems to be bug.

**Comment by FedorLap2006** [comment]
This is not a bug: `MinValues` can be `0`, `MaxValues` cannot.

**Comment by eslindsey** [comment]
Both are optional according to the [Select Menu Object Select Menu Structure](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure), so shouldn't they both be `*int`? The Discord default for `max_values` is 1, so a setting of 0 for `MaxValues` should not be omitted (this would likely result in an error from the gateway, but that would be the "correct" behavior).

> This is not a bug - `MinValues` can be `0`, `MaxValues` cannot.

While this may be the case (I didn't test it), I don't see the see where Discord describes it that way in the docs. They are explicit about `min_values`: "min 0, max 25," but `max_values` just says "max 25".

This is part of a larger issue, I think: discordgo uses this same pattern (`*int`, `int`) for [`MinValue`, `MaxValue`, `MinLength`, and `MaxLength`](https://github.com/bwmarrin/discordgo/blob/5571950c905ff94d898501e5a0d76895fa140069/interactions.go#L106). According to the [Application Command Option Structure](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure), all of these are also optional, and only `MaxLength` has a minimum of 1. **`MaxValue` can be 0, and *should be sent if it is set as such.*** (It is not because of non-pointer type coupled with `omitempty`.)

Having differing data types in discordgo, but not in the Discord spec is a bit confusing. It also makes for awkward code:
```go
ptr := float64(-10)
opts := discordgo.ApplicationCommandOption{
	Type:     discordgo.ApplicationCommandOptionInteger,
	Name:     "number",
	MinValue: &ptr, // -10
	MaxValue: 0,
}
```
Note that the above code should require an input range of -10 to 0, but it does not. [Link to Go Playground.](https://go.dev/play/p/o8IIBHoRoBJ)
