### ISSUE TITLE
Review all uses of "int".

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#232]
They should probably be int32 or int64.

**Comment by dmportella** [comment]
go int64 and all should be oke this app doesnt need to be really memory efficient.

**Comment by bwmarrin** [comment]
Yeah, I mean using just "int" makes it inconsistent across platforms.  So the plan is to change all instances of "int" to either int32 or int64 depending on which is actually needed.

**Comment by tsdtsdtsd** [comment]
@bwmarrin 
> to either int32 or int64

Is there a reason not to use smaller int or unsigned int if applicable? 
I was already working on this one, but I was using the smaller sizes too. E.g.:

``` 
type Event struct {
	Operation uint8           `json:"op"`
```

I chose uint8 because the api documentation says it's a value between 0-11 (https://discordapp.com/developers/docs/topics/gateway#gateway-op-codespayloads)

**Comment by dmportella** [comment]
no there is no reason other then as you dev things switching context between int8, int16, int32, int64, int 128 and the unsigned versions of it is really annoying. plus since we dont control discords public api they could one day say "right everyone all ints are bigints now" then we have to go change a ton of code.

**Comment by tsdtsdtsd** [comment]
It's not that much code but well, I'm fine with int32/64

**Comment by robbix1206** [comment]
Sorry bad reference

**Comment by tsdtsdtsd** [comment]
> Yeah, I mean using just "int" makes it inconsistent across platforms. So the plan is to change all instances of "int" to either int32 or int64 depending on which is actually needed.

Sorry for this off-topic question, but I have to ask:
if "int" is inconsistent across platforms in a library (logic says you're right), does that mean that Go's stdlib is also inconsisten across platforms? I mean because stdlib funcs nearly always use "int", even in cases where a int8 would be enough.

**Comment by jrbury** [comment]
Under the hood `int` is essentially `int32` on 32 bit machines, and `int64` on 64 bit machines. Go recommends that you just use `int` unless you have a very specific reason to use sized int type

**Comment by CarsonHoffman** [comment]
This seems superfluous when Discord doesn't give specific sizes for types.
