### ISSUE TITLE
Add support for registering a new account.

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#49]
The Register endpoint is already defined but need to create a function to interact with it.

**Comment by Rivalo** [comment]
The Register endpoint only registers an unverified account. It has no way of using the login() function, since there is no information to do an auth request.
For verifying the account (I haven't tested this, this is according to meewO on the discord server) the client sends a /user/@me PATCH request with the email and password in its payload.

**Comment by bwmarrin** [comment]
Ah, thanks @Rivalo that is very helpful info!

**Comment by Rivalo** [comment]
Yesterday for a test bot I already wrote a Register function in the style of the login function. 
`` func Register(u string, dg discordgo.Session) (token string, err error) {```

I could simply rewrite it for the Session interface and do a pull request, and maybe give the Verification function a try. Is development/forking done in the develop branch?

**Comment by bwmarrin** [comment]
Yup, please do all PR's against the develop branch.  Thanks for any help! I really do appreciate it.
