### ISSUE TITLE
Discord Categories

### ISSUE THREAD

**Issue by yamamushi** [bwmarrin/discordgo#510]
I went looking around for this and couldn't find any functions for creating categories, which are a type of channel iirc. 

I believe you can manage categories by searching for them in the channel list, but perhaps there could be more specific functions for managing them added?

**Comment by sn0w** [comment]
Possible duplicate of #495

**Comment by yamamushi** [comment]
I closed this, but I'm reopening it because while you can move channels into categories, I'm not sure that you can _create_ categories

**Comment by Seklfreak** [comment]
You can create categories like this:
`channel, err := session.GuildChannelCreate(guildID, "my new category", "4")`

I noticed that `GuildChannelCreate` does not use the ChannelTypes defined in structs.go. I will create a pull request to change that later if I don't forget it. I don't think sending `text` or `voice` as the channel type still works. This will be a breaking change in the API, but since the old way doesn't work anymore I think it should be fine.

**Comment by Seklfreak** [comment]
#511

**Comment by Necroforger** [comment]
There are also constants for the various channel types so you don't need to remember the numbers.
[https://godoc.org/github.com/bwmarrin/discordgo#ChannelType](https://godoc.org/github.com/bwmarrin/discordgo#ChannelType)
