### ISSUE TITLE
onEvent() has problem unmarshalling JSON

### ISSUE THREAD

**Issue by kevinzwang** [bwmarrin/discordgo#549]
My bot has been running normally for a few days, but suddenly this was logged to stdout:
```
2018/05/17 00:53:52 [DG0] wsapi.go:532:onEvent() error unmarshalling PRESENCE_UPDATE event, json: cannot unmarshal number 1526517831550.0 into Go value of type int
```

After this occurs, the code is still running, but the bot is no longer connected to Discord.

I do not believe it's an overflow since on my machine, type `int` is 64 bit.

**Comment by Seklfreak** [comment]
While I do get the same error once in a while, it doesn't affect my bots connection to Discord for me. Could that problem possibly lay in your bots code? Do you not receive any events at all anymore?

**Comment by kevinzwang** [comment]
I don't believe so but I haven't tested it completely. Yeah it happens extremely rarely.

**Comment by iopred** [comment]
That error will likely cause an invalid PresenceUpdate event to be created,
it's highly likely your code is not handling it correctly (like maybe it
tries to access User and has a NPE).

Annoyingly this is Discord sending bad data, hopefully it goes away.

**Comment by kevinzwang** [comment]
Ok thanks, I'll try to make my code handle it better.

**Comment by GTANAdam** [comment]
This is still the case and it's very spammy with crowded guilds

**Comment by bwmarrin** [comment]
We could adjust the error level of that message to a warning so it wouldn't be so spammy.  The issue here is that clients are sending bad data, and discord passes it along.  If you want to bump your logging up to debug and find out who's sending bad data - see if it's some other library or Discord itself.  If it's another Library you might be able to PR a fix to them.. I donno if there's anything we can do if it's just Discord itself.

**Comment by GTANAdam** [comment]
I've just disabled logging to avoid it but I'll look into it

**Comment by riking** [comment]
Where are known minor issues usually documented?
