### ISSUE TITLE
[Question] How to apply server mute for user by bot accout?

### ISSUE THREAD

**Issue by saulgoogman** [bwmarrin/discordgo#631]
Is there such an opportunity in **discordgo**? I take state of the member server mute in VoiceStateUpdate and save it in the database. I want to restore the mute after the user comeback to the server. This can be done now?

**Comment by MrDienns** [comment]
Seems more like a general programming question instead of being specific to this library.

If I understand your question exactly, you want to mute a user after leaving and rejoining a Discord server? If you keep your mute data somewhere in your own database, you could simply listen for a user join event, check your database and re-apply the mute role.
