### ISSUE TITLE
[Question] Voice packet loss compensation

### ISSUE THREAD

**Issue by xIAlexanderIx** [bwmarrin/discordgo#632]
Due the fact that the voice connection uses UDP, there is always the possibility of occurring some nasty packet loss, and while I was using a discord library from another language, I noticed that they have a compensation setting built-in which makes quite a difference in the audio quality.

I digged into their code and looks like they send the same packet multiple times to achieve that.

```javascript
_sendPacket(packet) {
    let repeats = this.streamOptions.passes;
    this._setSpeaking(1);
    while (repeats--) {
      if (!this.player.voiceConnection.sockets.udp) {
        this.emit('debug', 'Failed to send a packet - no UDP socket');
        return;
      }
      this.player.voiceConnection.sockets.udp.send(packet)
        .catch(e => {
          this._setSpeaking(0);
          this.emit('debug', `Failed to send a packet - ${e}`);
        });
    }
}
```

is there a possibility of implementing this feature? 

Bonus question haha...

I've used both dca and dgvoice to send audio, and both experience some nasty artifacts during the few first ms of the audio, not sure if this is related to packet loss, or if I'm doing something wrong haha. 

Anyone has experienced this?

**Comment by Hinara** [comment]
I don't see any loss compensation in this code it's just sending packets
The audio compensation is done by the opus format nothing can be done as UDP doesn't guarantee that the packet will be received

I didn't had any trouble with Opus audio encode in dca format. That's was the primary reason I switch to discordgo because at the given time I was using ffmpeg with discordjs if I remember but it cause a loss of 0.5s before and after the audio file which was disturbing as I was making a bot that was play meme sounds (which were about 3s), so I had to add blank before and after each audio

**Comment by xIAlexanderIx** [comment]
Ah, makes sense, while using discordjs I noticed the artifacts if I tried to play a file directly using their playfile method, but If I used a stream buffer it would play normally. 

I'm getting the same artifacts while using a dca buffer, Are you using bwmarrin's dca encoder? and what settings are you using for the encode.

**Comment by Hinara** [comment]
Ah it was about how discordgo was working at a given time, it had a big chan of AudioFrame so when I ask the bot to pause it still playing for 2-3s, to avoid the issue I've decided to put frame in the channel by myself with the same interval of time than discordgo send the audio frames

**Comment by xIAlexanderIx** [comment]
Ah, yeah, makes sense the use of a ticker, glad they changed that.

btw, looks like my net was indeed the cause of the artifacts, today It ran smoothly, thank you for your help!
