### ISSUE TITLE
HTTP 400 bad request on ChannelMessageSendEmbed with missing value

### ISSUE THREAD

**Issue by Heanthor** [bwmarrin/discordgo#726]
Hi,

I'm seeing a discord API error while using `ChannelMessageSendEmbed`. The error is:

`error="HTTP 400 Bad Request, {\"embed\": [\"fields\"]}"`

It seems like this is caused by an empty `value` key in the `MessageEmbedField` struct. `Value` is json tagged as `omitempty`, would it make sense to remove this tag so the key is sent every time?

**Comment by CarsonHoffman** [comment]
This isn't caused by the `omitempty` tag; field values cannot be an empty string on the API level.

**Comment by Heanthor** [comment]
Good to know, should discordgo throw an error for blank values then? The API response is non-specific and doesn't really help solve the problem.

**Comment by CarsonHoffman** [comment]
The library in general doesn't really check for invalid inputs, as these can change over time on Discord's end and there generally isn't a ton of documentation on exactly what inputs are rejected and what aren't. The impetus of ensuring inputs are valid is generally left to the user in these scenarios, and setting a precedent otherwise would require a large shift in library code; I know it's not an ideal solution, but the general mission of the library is to be as low-level as possible.
