### ISSUE TITLE
Net/http: TLS handshake timeout error

### ISSUE THREAD

**Issue by chand1012** [bwmarrin/discordgo#746]
I have been having an issue with my discord bot not being able to get channel data, claiming there was a TLS timeout error. The error only appears when attempting to get a channel name but it seems that it also tends to have this issue with just retrieving messages because the bot itself will randomly restart after being online for more than 30 minutes. I tested to see if this was my internet connection by spinning up a VPS and the issues persisted. It also isn't an architectural issue because I have moved it between a Raspberry Pi 4, a Vultr VPS instance, and a system I was using as a Minecraft Server (all Linux, as that's what the bot was designed for) and none of them seem to make any difference. I posted an issue about this (#745) but not much was accomplished there. I also mentioned there that it seemed that it was an issue with connected to the Discord API, and that a few spikes in API response time wouldn't cause weeks of issues. Here is a snippet from the error logs:
```
Mar 04 16:14:25 raspberrypi GoDiscordBot[2840]: Getting current channel names...
Mar 04 16:14:30 raspberrypi GoDiscordBot[2840]: Error getting channel name: Get https://discordapp.com/api/v6/guilds/<guild id>/channels: net/http: TLS handshake timeout Error getting channel name: Get https://discordapp.com/api/v
Mar 04 16:14:30 raspberrypi GoDiscordBot[2840]: Populating base post cache...
Mar 04 16:14:30 raspberrypi GoDiscordBot[2840]: New cache time is 1583342070
Mar 04 16:14:58 raspberrypi GoDiscordBot[2840]: Took 28411ms to add to cache.
Mar 04 16:14:58 raspberrypi GoDiscordBot[2840]: Resetting Blacklist...
Mar 04 16:14:58 raspberrypi GoDiscordBot[2840]: New Blacklist time is 1583349298
Mar 04 16:14:58 raspberrypi GoDiscordBot[2840]: Discord-Quick-Meme has started on 355 servers
```
The bot also seems to randomly crash without warning and restart itself. There are no messages in the log about the program crashing, just that it will reset its channel cache randomly. There is also a huge percentage of messages that are either really slow (up to a minute for the bot to receive the command) or those that seem to never make it to the bot, which I think could also be being caused by this issue. The code can be found [here](https://github.com/chand1012/Discord-Quick-Meme/). The long cache times are normal as that's the bot caching the most popular Reddit posts from the last 3 hours. I hope this is an error on my end as its probably not a huge burden to fix but I have looked and searched for the bug that could be causing this in my code and have found nothing that could cause this.

**Comment by ewohltman** [comment]
I'm not 100% sure what the root cause is, but I can say that I have been using `discordgo` for about 2 years now myself without seeing this kind of issue.

Some pointers I could give that might help:

* Update your project to use [Go modules](https://blog.golang.org/using-go-modules). This will help make it clear what version of your library dependencies are being used and to ensure reproducible builds. Double check that you're using the latest tagged version of `discordgo`
* Don't use the `errCheck` function that you have. Instead, explicitly check your errors at each site that an error can occur and handle it appropriately. See below for a relevant example
  * [Don't panic](https://github.com/golang/go/wiki/CodeReviewComments#dont-panic) because that will cause your application to halt immediately and can prevent `defers` from being called, buffers from being flushed, etc. Instead, handle or return errors up the call stack and if its a fatal condition, return/exit from the `main` function
* Avoid the usage of global variables because their state can change in sometimes unexpected ways. I've found whenever I felt the need for a global variable, I could instead use a `struct` to "encapsulate" the state. When using slices and maps in this way, you may also want to consider using [sync.Mutex](https://golang.org/pkg/sync/#Mutex) to prevent race conditions
  * Declaring variable like `var someName someType` will create the variable with the value set to that type's [zero value](https://golang.org/ref/spec#The_zero_value). Be careful here because for some types like pointers, slices, and maps, the zero value is `nil`
* Break your project into more, smaller packages instead of everything in `package main` to help define and encapsulate responsibility. This can also facilitate the writing of [tests](https://golang.org/pkg/testing/)
* Check out the built in [pprof](https://golang.org/pkg/net/http/pprof/) package to profile your application and get some insight as to what it's doing when things aren't going the way you expect them to
* Consider some kind of monitoring for your system/application to get historical data for things like CPU and memory utilization. A common and powerful combination frequently used is [Prometheus](https://prometheus.io/) to gather your metrics and [Grafana](https://grafana.com/) to visualize them


Error handling example (since this particular function is run in a goroutine we'd just log the error instead of returning it):

```go
func getAllWorker(discord *discordgo.Session, guildID string, send chan<- Server, wg *sync.WaitGroup) {
    defer wg.Done()
    ...
    channels, err := discord.GuildChannels(guildID)
    if err != nil {
        // Log the error and return
        // The return here is useful since we don't want to continue this function and possibly dereference nil pointers by mistake
        // There's also no need to send a `Server` struct down your `send` channel that only has nil slices
        fmt.Printf("Error getting channel name: %s", err)
        return 
    }
    ...
}
```

Hope this helps to better understand the issue that is occuring!
