### ISSUE TITLE
Why is Session.UserChannelPermissions deprecated?

### ISSUE THREAD

**Issue by qaisjp** [bwmarrin/discordgo#751]
This seems quite useful. It attempts to get info from state, and falls back on network.

The deprecation comment says "just use the state function", but the state function will happily return ErrStateNotFound, which is not ideal.

**Comment by bwmarrin** [comment]
Because it doesn't follow the pattern set by every other function within the library.  All state and rest api functions are entirely separated.   Having a one-off function that doesn't behave in the exact same way that all other functions behave is a bad thing :)

**Comment by qaisjp** [comment]
Okay - are replacement helper functions planned?

Trying the state and falling back on REST seems like a very common use case and I'm guessing most users expect the state to behave as a caching _layer_ rather than just a plain old cache.

```go
func (b *bot) Channel(guildID, channelID string) (*discordgo.Channel, error) {
	m, err := b.discord.State.GuildChannel(guildID, channelID)
	if err == nil {
		return m, nil
	}

	m, err = b.discord.Channel(channelID)
	if err == nil {
		return m, nil
	}

	return nil, err
}
```

In my opinion I find having to write helper functions, like the above code, quite painful and duplicative.

Is this something you want users to write their own library for? I think providing stuff like this somewhere would make your library a lot more user friendly.

**Comment by ewohltman** [comment]
I believe the intent of `discordgo` is to just be a low-level interface for the Discord API. Rather than having convenience functions in the library and then having to maintain that additional code (e.g. all cases of state lookups failing back to REST calls), the tools are provided for consumers to implement themselves like you showed in your example.

@bwmarrin please feel free to correct me if I'm off.

**Comment by qaisjp** [comment]
That makes sense, but I argue that the entire `discordgo.State` feature goes against that principle. Maybe I am misunderstanding the purpose of State.

I'd hope we can agree that users duplicating code like this is of little benefit to the community:

```go
func (b *bot) Channel(guildID, channelID string) (*discordgo.Channel, error) {
	m, err := b.discord.State.GuildChannel(guildID, channelID)
	if err == nil {
		return m, nil
	}

	m, err = b.discord.Channel(channelID)
	if err == nil {
		return m, nil
	}

	return nil, err
}
```

Even that code there is wrong. It should only be falling back if the first error returns `ErrStateNotFound`.

If the problem is having to maintain this extra code, we could even just auto generate the code using `go generate`. 

If you're open to a change like this, I'd be happy to submit a separate issue/proposal introducing a layer (or extension to State) that solves this problem.

Or if you don't think it's a problem or a problem that discordgo needs to solve, I'd be interested in understanding why. You probably have good reasons, and I simply don't know them.

**Comment by bwmarrin** [comment]
@ewohltman  is right. The State and the REST API have been completely separate since the library was built and it is intentional.  Everyone using it now and for the last 5 years has used it in that fashion.  

The reason a state even exists, is because Discord a few years ago told all the library developers they wanted all the libs to have a state built into them and it was a "requirement".

I'm open to the idea of changing this but it would take a lot of feedback from users to make sure we're not overlooking something.

If we were to change it, this func is still deprecated :)  I would opt to for having the functions within the State make calls to the API if they don't have a value opposed to the other way around.  I'd also probably push a change like that into a Version 2 of the lib where the State is a separate package entirely.
