### ISSUE TITLE
ChannelMessageSend big Latency

### ISSUE THREAD

**Issue by bimbimprasetyoafif** [bwmarrin/discordgo#776]
Hi, i just try ping pong example and modification pong to heartbeatlatency. i confuse about this response, over 300ms for just ping and pong
`if m.Content == "ping" {
		s.ChannelMessageSend(m.ChannelID, 
			fmt.Sprintf("%dms",s.HeartbeatLatency().Milliseconds()))
	}
`
anyone can explain why? or is there any mechanism that i miss?

**Comment by CarsonHoffman** [comment]
Could you elaborate on why you believe this to be a "big" latency? Your code has to wait for a network trip for the heartbeat (IIRC the API servers are all in the US East region, so that could be a consideration), and then your bot has to wait for Discord to do any internal processing of the event, actually send you the ack, then has to contend with another network trip over the WebSocket. Discord makes no guarantees about the speed at which it will dispatch events (or even if it will at all), so this doesn't seem unreasonable to me.

**Comment by bimbimprasetyoafif** [comment]
@CarsonHoffman That's make sense. so it's about network and all that things. thanks for your answer.
