### ISSUE TITLE
Question - How to take notes on user

### ISSUE THREAD

**Issue by nailuj29gaming** [bwmarrin/discordgo#847]
In Discord, regular users can take notes on users. Is it possible for a bot to do this too? 
![image](https://user-images.githubusercontent.com/54189157/101562457-76255300-3995-11eb-9c35-2d29135bfb03.png)
I attached a screenshot showing what I mean.

**Comment by Mexican-Man** [comment]
Taking a quick look at the Discord [docs](https://discord.com/developers/docs/resources/user), it doesn't look like this is a supported feature.

If your goal is to store and access custom data related to each user, the easiest and smartest way would be to set up some sort of database or file, and store your "notes" in there.

You can always make a suggestion from the [Discord suggestions page](http://feedback.discord.com/). Keep in mind that some features (similar to these) are intentionally left out, such as bots being able to set a custom status. So it might be by design.

**Comment by robertkozin** [comment]
https://pkg.go.dev/github.com/bwmarrin/discordgo#Session.UserNoteSet

**Comment by Mexican-Man** [comment]
Nice find. I found the notes object in the `SERVER_CREATE` event, but I kept my mouth shut cuz I didn't find the function. Serves me right I guess.
