### ISSUE TITLE
Add to Event Loop OR Create User Defined Event

### ISSUE THREAD

**Issue by mrgarelli** [bwmarrin/discordgo#864]
Hello,

# The Ask
In discord.py I am able to add an async function to the bot's event loop as explained in this [stack overflow post](https://stackoverflow.com/questions/51689285/how-to-add-a-function-to-discord-py-event-loop). Is this currently possible in discordgo? How exactly does the event loop work?

# The Reasoning
this is very useful for sending messages triggered by events in code rather than just by commands (i.e. responses to messages on the guild/server). For example if my python script is successful I may want to send an unprompted message to a discord server.

# Possible Solutions
* exposing and API method to add an asynchronous function to the event loop where messages can be sent at certain points [as is done in discord.py](https://github.com/Rapptz/discord.py/blob/master/examples/background_task.py)
* giving the developer/user the ability to declare & dispatch their own events that could be associated with handlers just like the discordgo events in events.go

**Comment by CarsonHoffman** [comment]
Is there any particular reason you can't just start up a background goroutine in your program (outside the scope of DiscordGo)? Functions in `Session` are safe to be called concurrently.

**Comment by mrgarelli** [comment]
> Is there any particular reason you can't just start up a background goroutine in your program (outside the scope of DiscordGo)? Functions in `Session` are safe to be called concurrently.

I haven't found an example of this, but I will give it a try. If I can figure it out are you open to a PR in [examples](https://github.com/bwmarrin/discordgo/tree/master/examples)?

**Comment by CarsonHoffman** [comment]
I don't mean to be patronizing, but this seems like much more of a core language question than something specific to DiscordGo. The concurrency model of Go encourages spawning goroutines when necessary (laptops can easily handle tens of thousands of concurrently-running goroutines, especially if most are in a waiting state, like waiting for some network I/O or waiting for a signal from another goroutine); idiomatic Go programs typically don't explicitly use some sort of event loop because it simply isn't necessary, and rather than interfacing with a library to coordinate your concurrency you'd usually simply spawn your own goroutines external to it. Being able to run code around multiple concerns concurrently is a core skill in Go, and there isn't much that differentiates doing such in DiscordGo versus any other Go code. I'd recommend going through [the concurrency section in the Go Tour](https://tour.golang.org/concurrency/1) or [Go by Example](https://gobyexample.com/goroutines) if you haven't already—they're both great resources.

**Comment by mrgarelli** [comment]
I understand. Thank you for the guidance. I am certainly an amateur Gopher. And apologies for clearly bringing this in incorrect forum.

**Comment by mrgarelli** [comment]
In case anyone does wonder the same thing, here is the simplest [example of background process sending messages to discord server](https://github.com/mrgarelli/goTryThings/blob/master/discord_reporter/main.go) that I could come up with. Also here is [entry point for goroutines examples](https://gobyexample.com/goroutines), a key concept I was missing out on.
