### ISSUE TITLE
Bot triggers GuildCreate event again for all the servers it was previously in.

### ISSUE THREAD

**Issue by barbarbar338** [bwmarrin/discordgo#955]
I need to do a database operation for the servers that bot has just joined, but when I use the discordgo.GuildCreate event, bot triggers the event again for the servers it was previously in.

Here is my code:
```golang
package events

import (
	"github.com/barbarbar338/emojibot/utils"
	"github.com/bwmarrin/discordgo"
)

func GuildCreate(session *discordgo.Session, event *discordgo.GuildCreate) {
	utils.Logger.Println("I joined server", event.Name)
}

// in main
// discord.AddHandler(events.GuildCreate)
```

and this is my output: 
```
PS C:\Users\demir\Desktop\emoji-go> go run .
✔ - 2021/06/19 11:51:28 main.go:34: Logged in as Emojicord BETA
☄ - 2021/06/19 11:51:28 ready.go:10: Ready!
✎ - 2021/06/19 11:51:28 guildCreate.go:9: I joined server Merloss's emojis << these shouldn't be here
✎ - 2021/06/19 11:51:28 guildCreate.go:9: I joined server Hammer Sunucusu << these shouldn't be here
☄ - 2021/06/19 11:51:31 main.go:45: Closing bot...
PS C:\Users\demir\Desktop\emoji-go> 
```
![image](https://user-images.githubusercontent.com/35371155/122636964-bf98ec80-d0f4-11eb-874e-451d407fdbd7.png)

**Comment by CarsonHoffman** [comment]
This is fully expected behavior. Looking at the [Discord docs](https://discord.com/developers/docs/topics/gateway#guild-create), we see:
> This event can be sent in three different scenarios:
> 1. When a user is initially connecting, to lazily load and backfill information for all unavailable guilds sent in the Ready event. Guilds that are unavailable due to an outage will send a Guild Delete event.
> 2. When a Guild becomes available again to the client.
> 3. When the current user joins a new Guild.

This event more closely means "this guild is now available to your current running instance" to "this guild is now available to your bot at all". If you'd like to detect guild *joins*, you should keep some sort of external long-running storage, or could perhaps try using the `JoinedAt` time in your bot's member object in the guild to approximate it.

**Comment by barbarbar338** [comment]
Thanks for your reply :)
