### ISSUE TITLE
ActivityType struct is Incomplete

### ISSUE THREAD

**Issue by vertex-admin** [bwmarrin/discordgo#958]
For some reason, ActivityTypeWatching is commented out in structs.go with the comment "// not valid in this use case?"

It works just fine and we should uncomment it:
```go
err := bot.UpdateStatusComplex(discordgo.UpdateStatusData{
	Activities: []*discordgo.Activity{
		{
			Name: "you",
			Type: discordgo.ActivityTypeWatching,
		},
	},
	Status: "online",
})
```

**Comment by MrFastDie** [comment]
There is a 5th type aswell (Competing) https://discord.com/developers/docs/topics/gateway#activity-object-activity-types

Furthermore many more posibilities have been added to the activity: https://discord.com/developers/docs/topics/gateway#activity-object

I've come along this since setting emojies as unicode stopped working
